id: P008253
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG9037
  title: འོད་གསལ་རྒྱན་གྱི་བཤད་པ།
  author: ''
  volumes:
    578ec8169308480a9c2cb625064b875a:
      image_group_id: I1KG9066
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
