id: ICC534A6C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:18:19+00:00'
last_modified: '2022-06-08T08:15:34.047131+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9037
  title: འོད་གསལ་རྒྱན་གྱི་བཤད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B9BB:
      image_group_id: I1KG9066
      title: ''
      total_pages: 388
      order: 1
      base_file: B9BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
